version: '3.7'
services:
  gestorcontenedores:
    build: .
    container_name: gestorcontenedores
    image: andresgarcia0313/portainer:latest
    ports:
      - 9000:9000
      - 8000:8000
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
