version: '3.8'
services:
  contenedorizador:
    build: .
    container_name: portainer
    image: andresgarcia0313/portainer:latest
    ports:
      - 9000:9000
      - 8000:8000
      - 9443:9443
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
